# Sangbok-Apache-Redirect-Compatibility-Testing (SARCT)
version: "2.4"
networks:
    sangbok-net:
services:
    apache:
        image: httpd:2.4.46-alpine
        container_name: sarct-apache
        volumes:
            - ./apache.conf:/usr/local/apache2/conf/httpd.conf:ro
        networks:
            - sangbok-net
        ports:
            - 80:80/tcp
    sangbok:
        # Use this for the latest version
        build:
           context: ../..
           dockerfile: docker/nginx/default.Dockerfile
        # Use this (or similar) instead for update testing
        # Note that certain files are indexed by commit, which may cause certain cache problems when using this testing method.
        # image: ghcr.io/fysiksektionen/sangbok-html@sha256:73a7e635c2046609a032b5399cd056320cf81d02c1ee5ee95091b0aba12888fd
        container_name: sarct-sangbok
        restart: unless-stopped
        ports:
            - 81:80/tcp
        networks:
            - sangbok-net