# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:
    paths:
      - '**.vue'
      - '**.ts'
      - '**.tsx'
      - '!**.test.ts'
      - '**.js'
      - '**.jsx'
      - '**.json'
      - '**.mscz'
      - '**.conf'
      - '**.go'
      - 'Dockerfile'
      - '.Dockerignore'
      - '**/build-vue.yml'
  pull_request:
    branches: [ main, dev ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: fysiksektionen/sangbok-html

jobs:
  ##
  ## Build zip file to export
  ##
  build:
    runs-on: ubuntu-latest
    name: Build vue
    needs: sheet-music
    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x, 18.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install packages
      run: npm ci
    - name: Fetch sheet music artifacts
      uses: actions/download-artifact@v2
      with:
        name: music-svgs
        path: public/msvg
    - name: Unpack sheet music artifacts
      working-directory: public/msvg
      run: mv svgs.json ../../src/assets/msvgs.json
    - name: build
      run: npx vue-cli-service build
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      if: ${{ matrix.node-version == '18.x' }}
      with:
        name: dist-node-${{ matrix.node-version }}
        path: |
          dist
  
  ##
  ## Sheet music generation
  ##
  sheet-music:
    runs-on: ubuntu-latest
    name: Generate sheet music resources
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - name: Install svgo
      run: npm install -g svgo
    - name: Install MuseScore 3
      run: sudo apt-get update && sudo apt-get install musescore3
    - name: Unpack cached svg:s
      run: rm -rf svg && tar -xJf svg.tar.lzma
      working-directory: ./music
    - name: Convert mscz to compressed svg:s (from cache)
      working-directory: ./music
      run: ./convert.sh --compress --no-move
      if: ${{ github.ref != 'refs/heads/main' }}
    - name: Convert mscz to compressed svg:s (from scratch)
      working-directory: ./music
      run: ./convert.sh --compress --no-move --force-on-change
      if: ${{ github.ref == 'refs/heads/main' }}
    - name: Compute hashes
      working-directory: ./music
      run: sha1sum mscz/*.mscz
    - name: Perpare for export
      working-directory: ./music
      run: mv svgs.json svg
    - name: Archive cache for future use
      uses: actions/upload-artifact@v2
      with:
        name: music-svgs-cache
        path: music/svg.tar.lzma
      if: ${{ github.ref == 'refs/heads/main' }}
    - name: Archive mscz folder hash for future use
      uses: actions/upload-artifact@v2
      with:
        name: sha1
        path: music/mscz.sha1
      if: ${{ github.ref == 'refs/heads/main' }}
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: music-svgs
        path: music/svg
  
  ##
  ## Docker build
  ##
  docker:
    runs-on: ubuntu-latest
    name: Build Docker containers
    needs: sheet-music
    strategy:
      fail-fast: false
      matrix:
        variant: [default, gz, gz-br]
        include:
          - variant: default
            compression: semi-redundant gzip/brotli
            server: nginx
          - variant: gz
            suffix: -nginx-gz
            compression: gzip
            server: nginx
          - variant: gz-br
            suffix: -nginx-gz-br
            compression: redundant gzip/brotli
            server: nginx
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Fetch sheet music artifacts
        uses: actions/download-artifact@v2
        with:
          name: music-svgs
          path: public/msvg
      - name: Unpack sheet music artifacts
        working-directory: public/msvg
        run: mv svgs.json ../../src/assets/msvgs.json
      # Login against a Docker registry except on PR(https://github.com/docker/login-action)
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # Extract metadata (tags, labels) for Docker (https://github.com/docker/metadata-action)
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: | 
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=edge,branch=dev
            type=ref,event=branch
          flavor: |
            suffix=${{ matrix.suffix }}
      - name: Build and push Docker image (${{ matrix.server }} with ${{ matrix.compression }} precompression)
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          file: docker/${{ matrix.server }}/${{ matrix.variant }}.Dockerfile
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}